name = "cors"
main = "src/index.ts"
compatibility_date = "2022-11-24"

kv_namespaces = [
    { binding = "ANALYTICS", id = "f71db540fac3473eaec147352eef5cc0", preview_id = "4daadfc8c22742acab5fb924892f76a9" },
]
